name: the_acquaintances
favicon: null
layout_spectrum: 0.3063824495766312
typography_spectrum: 0.22474569384939969
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.6969687948003411
  lightness: 0.84211280872114
  saturation: 0.17510069929994643
  rhythmicContrast: 0.5991000097710639
purpose: []
